version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: orange
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always
  redis:
    container_name: v-reids
    image: redis:5.0.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/etc/redis
    tty: true
    command: redis-server /etc/redis/redis.conf
  orange:
    restart: always
    container_name: v-orange
    ports:
      - 8011:8011
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - nginx
      - mysql
      - redis