spring:
  datasource:
    url: jdbc:mysql://mysql:3306/orange?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    open-in-view: true
  #redis配置
  redis:
    host: redis
    port: 6379
    database: 1
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
server:
  port: 8012
