spring:
  datasource:
    url: jdbc:mysql://47.111.70.169:3306/orange?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zzc
    password: qaioasd520
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
          #auto: update
    open-in-view: true
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
server:
  port: 8011