spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orange?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    open-in-view: true
server:
  port: 8011