spring:
  datasource:
    url: jdbc:mysql://mysql:3306/orange?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #          auto: create
          auto: create
    open-in-view: true
  #redis配置
  redis:
    host: 47.111.70.169
    port: 6378
    database: 1
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    password: qaioasd520
server:
  port: 8011