spring:
  datasource:
    url: jdbc:mysql://47.111.70.169:3306/orange?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zzc
    password: qaioasd520
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    open-in-view: true
server:
  port: 8011